### ISSUE TITLE
stop treating scans as models in their own right, treat scans as a property of players

### ISSUE THREAD

**Issue by AKST** [ITatJCU/hunter#15]

**Comment by axrs** [comment]
Can you elaborate on this for us? Links, anything?

Are you thinking for the translator pattern?

**Comment by AKST** [comment]
Oh this is just for the client side representation.

In ember, models are persistent entities, that generally have their own end point, whereas scans is just a property of the player model.

A transformer is just a Jason parser thing, I'll link the docs http://emberjs.com/api/data/classes/DS.Transform.html 

Better title would be make a transformation for scan property of player model

**Comment by AKST** [comment]
Apologies I made the issue as a reminder for myself haha, I forgot others would probably want to be read it as well

**Comment by AKST** [comment]
To be a bit more clear, the purpose of a transformer is to turn a javascript object into an ember object. 

Ember has it's own version of [Objects & Classes](http://guides.emberjs.com/v1.10.0/object-model/classes-and-instances/), to provide stronger abstraction capabilities (like observers, computed properties, mixins) and to make up for some short comings of the javascript object model.

**Comment by AKST** [comment]
Done, I forget when tho
